# Generated by Django 3.2.8 on 2021-10-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
