# Generated by Django 3.2.8 on 2021-10-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hakage', '0002_auto_20211009_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='hacaton5/media'),
        ),
    ]
